// <auto-generated />
namespace CodeFirst_EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class RenameKategoriAdInKategoriIsimToKategorisTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameKategoriAdInKategoriIsimToKategorisTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202210261209237_RenameKategoriAdInKategoriIsimToKategorisTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
